// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkzdnkccozhaurjhrsqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZremRua2Njb3poYXVyamhyc3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTUwODksImV4cCI6MjA1OTkzMTA4OX0.OKPxOmYy613vUZOqarWLfVhbYxWW-xEJVy8rtxx88vQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);